#define DSQW_BASE_ADDR 		XPAR_DESKEW_TOP_0_BASEADDR

//-----------DESKEW TOP REGISTER ADDRESSES---------//
#define DSQW_CFG_REG 		(DSQW_BASE_ADDR + 0x00)
#define DSQW_START_ADDR_REG (DSQW_BASE_ADDR + 0x04)
#define DSQW_IMG_DIM_REG 	(DSQW_BASE_ADDR + 0x08)
#define DSQW_STAT_REG 		(DSQW_BASE_ADDR + 0x0C)
#define DSQW_ACK_REG 		(DSQW_BASE_ADDR + 0x10)

#define DSQW_IRQ_ID XPAR_FABRIC_DESKEW_TOP_0_DESKEW_IRQ_INTR
#define INTC_DEVICE_ID 		XPAR_PS7_SCUGIC_0_DEVICE_ID

#define BRAM_BASE_ADDR XPAR_BRAM_0_BASEADDR
#define BRAM_END_ADDR  XPAR_BRAM_0_HIGHADDR
